[project]
name = "mcp-weather-python"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "mcp[cli]>=1.10.0",
    "requests>=2.32.4",
]
